---
title: "Spatial patterns on tourism establishments in five CIP in Mexico, 2010-2022"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
bibliography: D:\\stm\\bibligraphy\\bibliography.bib
csl: D:\\stm\\bibligraphy\\regional-science-and-urban-economics.csl
---

# Abtract

Studies on spatial patterns on economic activity contributes to management, planning and fostering economic performance since investors, policy makers and social organizations have valuable information about where and why activity is concentrated. Spatial patterns on tourism has been studied to organize tourist flown to take better advantage of existing infrastructure, planning new one and promoting new tourism facilities and for conservative purposes of natural areas . Central Mexican government started projects aimed to construct big tourism facilities offered fundamentally to foreign visitors at the end of sixties. They were called _centros integralmente planeados_ or "fully planned centers" (CIP) headed by FONATUR (Fondo Nacional de Fomento al Turismo). The objective of this article is to explore spatial distribution patterns of tourism establishments in five municipalities where the CIP are located. This may contribute to evaluate how patterns differs among CIP and help planners, managers, local associations and entrepreneurs to decide where other potential activities may be located and to evaluate the performance of the existing ones. The results show that...

# Introduction  

Between 1993 and 2021, the share of tourism on Mexican Gross Domestic Product (GDP) was around 8.2%. In 2019, the previous year of the pandemic for COVID19, this share reached 8.5%. Almost 2.3 millions persons were employed in the sector, around 5.8% of total employment in Mexico [@INEGI2018cn]. In 2022, 65.9 millions of travelers were registered entering in Mexico, 58% from them were international tourist [@BANXICO2022].

In January 2023, the balance of international travel account of balance of payments was positive and reach almost 2.1 billion dollars, and even during the pandemic showed a positive balance [@BANXICO2022]. The tourism has contributed to reduce external constraint of balance of payments which had been a typical problem to growth in economies like Mexico [@Pick2005; @Cruz2010].

Mexican central government had actively promoted tourism sector. In middle seventies, Mexican government launched Cancún tourims complex as the first of the _Centros Integralmente Planeados_ project or "Fully Planned Centers" (CIP). Nowadays Cancún CIP is the best known Mexican tourist destination in the World [@Fonatur2020]. 

According to Tulio and Santamaría [-@Tulio2015], CIPs own 40% of coastal hotels in Mexico, attracting 20% of international tourists, generating 44 cents per dollar in tourism, owning 18% of 5-star hotels, and 54% of foreign exchange spent by visitors. They generated 172 thousand jobs in 2012. On January 2018, 2.9 millions rooms available  for lodging were registered by SECTUR. They are uneven distributed among Mexican states, mainly at Cancún in Quintana Roo and Los Cabos in Baja California states. This two destinations has CIP and concentrate about 47.3% and 21.4% of rooms available, on one hand, and 37.3% and 19.4% of tourists arrivals, on the other [@DataTur2023]. From the five original projects, these two had been tremendously succeed in the way originally planned [@Tulio2015], while the others have had heterogeneous results. 

The roll of planning has been recognized in regional sciences and tourism management for the explicit spatiality of the tourism resources. Spatial distribution of resources attractions and tourism establishments is a central topic in planning and management, for the government and for the private sector. There is an increasingly amount of studies that explore the spatial distribution of tourism activities and their links to social and economic growth [@Wang2022], conflict management between stakeholders and planning authorities aimed to tourism development and conservation [@Almeida2017; @Derek2019]. Geolocated information resources provided by social media could help either to a better understand on spatial tourist patterns and to planning building infrastructure [@Kang2018] and protect natural areas [@Akerma2021].

Knowing on the spatial distributions of the tourism establishments in the five CIP could provide valuable information to managers, policy makers amd stake holders to understand the different performance among them to foster specific areas in the CIP by promoting new business opportunities. Furthermore, it is recognized that spatial analysis could improve social and economic life by: i) mitigating negative externalities, ii) providing a coordinating mechanism among social actors, iii) providing ways to share information and facilitate communication, iv) promoting collective decisions and v) a common language to discus and resolve problems [@Chettiparamb2012: 216]. This is particularly important in the context of conflict management related to the resistance and discomfort of tourism in recent years [@Ghermandi2020], or to determinate where and what kind of infrastructure should be bought to maximize financial returns [@Kang2018].

The objective of this article is to explore the spatial distribution patterns of tourism establishments in five CIP which report data in the National System of Statistical Information of the Tourism Sector of Mexico, DATATUR [-@DataTur2023]: Los Cabos, Loreto, Ixtapa-Zihuatanejo, Cancún and Bahías de Huatulco. By doing so, it is expected to have information of their concentration and orientation patterns  of the tourism establishments capable to be used in evaluating tourism activities for planners, managers, local associations and entrepreneurs which could be useful to know where other potential activities could be located and to evaluate the performance of the existing ones. 

The remain of the document is structured as follows. In section 1, we present more details about the CIP. In section 2, we carry out a literature review on tourism spatial patter analysis. Meanwhile, in section 3 the used methods are exposed, as well as the data sources. Section 4 shows the results, discussion and some final reflections on the spatial patterns founded. 

# 1. Fully Planned Centers in Mexico

Distribution of tourism activities in Mexico is the result of at least two factors. First, uneven allocation of natural, cultural and other points of tourism interest. Second, government planning (of absent of it), as CIP have been [@Pick2005; @Cruz2010]. In late sixties, Mexican government started to promote actively planned tourism development with the CIP project. This was headed by National Fund for Tourism Promotion (FONATUR) in order to reach regional development and foreign exchange inflows. The size and scale of some CIP make them have not only regional impact, but national [@Torres2008].

The central government led the CIP project through feasibility studies, financial resources and subsidies to private enterprises. The CIP were conceived as a mechanism to generate foreign exchange to alleviate pressures on the balance of payments and promote regional development. Therefore, Bank of Mexico and Ministry of Finance have played a leading role in the original development of this project, although they were formally headed by FONATUR [@Tulio2015]. Originally, Mexican authorities had planed constructing five CIP: Los Cabos, Loreto, Ixtapa-Zihuatanejo, Cancún and Bahías de Huatulco. Nevertheless, there are two more projects on going currently: Bahía de Banderas and Playa Espíritu [@Fonatur2020].

The results of the CIP are unequal. While Cancún and Los Cabos are the most succeed and concentrate more than half of the available rooms, the rest of the CIP have not had the same notable performance. Besides, the CIP as tourism promotion model has been seriously criticized, since  environmental degradation, socioeconomic inequality, and a lack of economic diversification are present in there [@Montaño2017].

The majority of available studies on CIP are about social and environmental issues, on one hand, and performance, on the other. Mostly of them focus in only one and rarely compare two of them. Related to environmental and social issues, there are studies on Cancún [@Torres2008], Los Cabos [@Montaño2017], Huatulco [@Monterrubio2012;@Mendoza2011] and some comparatives [@Monterrubio2018]. 

Torres and Momsen [-@Torres2008], based on an overview of public policies and interview with key actors, analyze the effects Cancún CIP on equity and regional development. That CIP has been an important driver for economic growth, yet has resulted in socioeconomic and environmental inequalities since has been oriented to elite tourist destinations, resultating in local marginalization and environmental degradation in some areas. They suggest a more equitable and sustainable approach to local tourism development that take into account the interest of local communities about taking decisions on tourism management. Montaño et al. [-@Montaño2017] evaluate the performance of Los Cabos CIP from sustainable point of view. For them, Los Cabos has undergone a rapid tourist development in the last four decades, which has generated significant economic benefits for the region. However, a series of challenges and problems associated with tourist development have also been identified, including environmental degradation, socioeconomic inequality, and a lack of economic diversification. Huatulco CIP has been studied by Monterrubio et al. 
[-@Monterrubio2012] and Mendiza et al. [-@Mendoza2011]. The studies show people perception who lived in Huatulco CIP through a representative survey. They perceive both positive and negative impacts of tourism in their community as job creation and improvement of local infrastructure and services, but increasing living cost and cultural identity loss. The authors highlights the importance of considering the perceptions and experiences of local residents in CIP planning and management. Monterrubio et al. [-@Monterrubio2018] compare socioeconomic impacts of three CIP: Cancún, Ixtapa-Zihuatanejo, and Los Cabos. They underline economic dependence on foreign capital and a non diversified economic structure with a very little benefits to the local residents. The importance of more equitable and participatory tourism planning is highlighted in order to reduce economic dependence and improve the distribution of benefits in local communities.

About CIP performance, some studies have trated Ixtapa [@Hernández2006], Huatulco [@Piñon2019] and the CIP located in Baja California Sur state (Los Cabos and Loreto). Hernández et al. [-@Hernández2006] study the image, satisfaction and loyalty of 140 foreign tourist at Ixtapa-Zihuatanejo CIP through a survey. Results indicate that CIP image is positive, with high tourist satisfaction with the tourism services offered and a high intention to return. From the perspective of the planning and management of smart tourist destinations, Poñón et al. [-@Piñon2019] study Huatulco CIP using interviews and direct observation. They identified different areas where technology and innovation could improve the tourist experience, such as information management, tourism promotion, mobility, sustainability, and security. Montaño et al. [-@Montaño2019] studied local development disparities in Los Cabos and Loreto CIP. Despite Los Cabos and Loreto were both planned and managed by SECTUR, their performance as tourist destinations and effects on local development are different: while Los Cabos has experienced a fast tourism and economic growth Loreto has challenged slowly growth and has bet to a more sustainable approach

This review highlights the extensive research conducted on the performance and multiple challenges faced by CIPs. While they have been found to have a positive impact on regional growth, this growth has been accompanied by issues of inequality and environmental degradation. However, no studies were found that specifically addressed the spatial distribution of tourism establishments in CIPs. 

# 2. Studing Spatial distribution tourism activities

The study of the spatial distribution of economic activity and its patterns has been a prolific field throughout the twentieth century up to now. Since Tobler's work on economic and urban growth, where he identified an empirical regularity known now as Tobler's first law of geography [-@Tobler1970], there has been significant interest in identifying causes and consequences of spatial regularities in economic activity and developing spatial statistics to detect and measure such regularities.

Spatial statistics and formal evaluation of spatial patterns relies on the seminal work of Cliff and Ord who propose techniques for measure spatial autocorrelation [@Renshaw1982onCliffOrd; @Wrigley1982onCliffOrd], essentially from a geographical point of view. Their contributions were improved by Getis and Ord [-@Getis1992] through new ideas which consider different types of distances involved in geographical relations . In social and economic studies, the work of Anselin [-@Anselin1988] has been fundamental not only extending the notion of spatial autocorrelation to social sciences field, but proposing new methods for detection and treatment of spatial autocorrelation through spatial econometric models.

Analysis of spatial patterns is important not only in the field of regional science, yet other fields. Spatial patterns on tourism activity has been widely studied in relation with planning, management, and economic promotion through new business opportunities. Chettiparamb et al. [@Chettiparamb2012] examine the relationship between tourism and spatial planning in order to regulate it. They suggest that spatial planning could be an effective tool to tackle the challenges of regional tourism, leveraging opportunities and emphasizes community participation and cooperation in tourism planning. 

Blasco et al. [-@Blasco2013] propose a new approach to delimitate tourism regions beyond administrative boundaries based on the spatial distribution of attractions, particularly in mountain regions. They use hierarchical cluster analysis to group and classify attractions in nine regions in Pyrenees mountains, independently of administrative boundaries. Through the Anchor Point Theory, Kang et al. [-@Kang2018] study the spatial structure of the tourist attractions in Korea capital with, among others methods, constructing local indicators of spatial association.

Rodrígez et al. [-@Rodríguez2020] studied the spatial distribution and intensity of tourism in Extremadura, Spain, and its relationship with the geographic, social, and economic characteristics of the region. They calculated density of tourism establishments and Moran's index to measure intensity and spatial autocorrelation, respectively. They found association between tourism intensity and accessibility, cultural and heritage presence, and even climate.

Guedes et al. [-@Guedes2015] examine how tourism packages for mainland Portugal are organized by looking at the cultural tourist attractions and the number of overnight stays allocated to each municipality. Their goal is to identify patterns in how different areas are grouped together and routes tourists typically take. This approach aims to provide an alternative to polarized spatial layout created by mass tourism in Portugal since 1965, which has been replicated in the Algarve region after the construction of the international airport in Faro.

Based on a typology of tourism and tourist in the Great Lakes Regions in Poland, Dekek et al. [-@Derek2019] study travel patterns through cluster analysis on survey data to understand different patterns and concentration to contribute a better planning and tourism management. Akerma et al. [-@Akerma2021] studies the spatial patterns and factors influencing tourism in the Bahamas through social media data, as well as estimates visits and tourism expenditure for support sustainable planning and management in marine protected areas. On the basis of spatial planning, i.e. ideal placement of tourist paths and the spatial arrangement of the infrastructure, Dunets et al. [-@Dunets2019] propose a project of health tourism in Russia trying to balance the stakeholders interest and the nature preservation. 

Even we could not identify any study on CIP spatial distribution of tourism establishments for Mexico, there are some studies about spatial distribution on some other tourism regions actually. Pick et al. [-@Pick2005] analyzed the tourist development in Mexico and its spatial patterns through the relationship between tourism and national economy, regional dependence on tourism and spatial concentration of tourist activity. Their analysis shows that tourist activity is concentrated in certain regions, and there is not an excessive economic dependence on tourism in some areas, which may lead to economic and environmental vulnerabilities in case of a decrease in tourist demand.

Spatial distribution of cultural and ecological tourism that highlights the connection between a place's history, cultural heritage, and natural environment is studied by Ghermandi et al. [-@Ghermandi2020]. They distinguish between local, national and international geolocated photographs to describe spatial patterns of tourism in the Usumacinta floodplain in Southern Mexico. They found that the hot spot of cultural services have so much more international visitors.

Understanding spatial patterns of tourism establishments in CIPs could help to promote sustainable development, improving quality of life of local communities and finding new bussiness oportunities that managers can take. 

# 3. Data and methods

An in-deep study of Exploratory Spatial Data Analysis (ESDA) tools including spatial point pattern could be reviewed in Bivand [-@Bivand2010]. In order to investigate the spatial pasterns and concentration of tourism establishment in the five CIP we use: i) average nearest neighbor index, ii) standard deviation ellipse, iii) spatial kernel density,  and iv) local indicator of spatial autocorrelation.

## Average nearest neighbor index

Average nearest neighbor index (ANNI) is a measure of clustering using point data. ANNI compares actual distance between the two nearest points ($\bar D_O$) to a theoretical random distance pattern ($\bar D_E$), that is [@ESRI2023a]:

$$
ANNI=\frac{\bar D_O}{\bar D_E}
$$
Where actual distance and expected distance are, respectively:

$$
\begin{aligned}
\bar D_O &=\frac{\sum_{i=1}^nd_i}{n} \\
\bar D_E &=\frac{0.5}{\sqrt \frac {n}{A}}
\end{aligned}
$$
Beside, $d_i$ is the observed distance between two nearest points, $n$ is the total number of points, $A$ correspond to the rectangular area that cover all points. An ANNI value less than 1 indicates clustering, meanwhile an ANNI more than 1 reflects dispersion [@spatialEco2021].

## Standard Deviational Ellipse

Standard Deviational Ellipse (SDE) is a measure that show graphically  dispersion or spread and orientation of a point data set [@Yuill1971; @ESRI2023b] which is useful to observe their spatial distribution. It is a ellipse that surround sixty three percent of the point distribution. Here we use Yuill method with QGIS plug-in developed by Tveite [-@tveitesde2016]. Following to Wang et al. [-@Wang2022] the SDE is constructed first identifying the center made of two coordinates ($SDE_x$, $SDE_y$) of the ellipse using arithmetic mean center for $x$ ($SDE_x$) and $y$ ($SDE_y$, respectively:

$$
\begin{aligned}
SDE_x &=\sqrt{\frac{\sum^n_{i=1}(a_i)^2}{n}}\\
SDE_y &=\sqrt{\frac{\sum^n_{i=1}(b_i)^2}{n}}
\end{aligned}
$$
Where $a_i=x_i-\bar x$ and $b_y=y_i-\bar y$. Again, following to Wang et al. [-@Wang2022], rotation of the ellipse is calculated as follow:

$$
tan \theta=\frac{A+B}{C}
$$

Where:
$$
\begin{aligned}
A &=\sum_{i=1}^n a_i^{2}-\sum_{i=1}^n b_i^{2}\\
B &= \sqrt{(\sum_{i=1}^n a_i^{2}-\sum_{i=1}^n b_i^{2})^2+4(\sum^i_{i=1}a_ib_i)^2}\\
C &=2\sum^i_{i=1}a_ib_i
\end{aligned}
$$
The length of the $x$ ($\sigma_x$) and $y$ ($\sigma_y$)axis are:

$$
\begin{aligned}
\sigma_x &=\sqrt{2}\sqrt{\frac{\sum^n_{i=1}(a_icos\theta-b_isin\theta)^2}{n}}\\
\sigma_y &=\sqrt{2}\sqrt{\frac{\sum^n_{i=1}(a_isin\theta-b_icos\theta)^2}{n}}
\end{aligned}
$$

## Spatial kernel density

Spatial kernel density (SKD) is a visualization of clustering based on the quartic kernel density of points density. The function of kernel density could be written as [@LuoCao2019: 6]:

$$
f(j)=\frac {1}{h^2}\sum[\frac{3}{\pi}(1-\frac{d_{ij}^2}{h^2})^2]
$$

We present results of SKD with heatmap, a geographic data visualization that show spatial concentration as more colored areas in a map. We construct heatmaps with interpolation tools in QGIS using a input point vector layer which result in a raster layer with density values. Raster layer is representet with this specific settings: singleband pseudocolor as render type where min and max values are default and linear interpolation with continuous classification.


## Global and local indicators of spatial autocorrelation

Finally, we use Moran global ($I$) and local indicator of spatial correlation ($I_i$). Anselin´s [-@Anselin2020moran] notation for Moran Index is:

$$
I = \frac{\sum_i\sum_j w_{ij} z_i.z_j /S_0}{\sum_i z_i^2 / n}
$$
Where  $w_{ij}$ are the elements of the weight matrix, $z_i = x_i - \bar{x}$, which is the variable in mean deviations, $S_0 = \sum_i \sum_j w_{ij}$ and correspond to the total sum of elements in the spatial weight matrix. The Moran´s $I$ measures global patterns of spatial autocorrelation and has values between -1 and 1 for negative and positive spatial autocorrelation, respectively. On the other hand, local version of Moran´s Index in Anselin´s [-@Anselin2020local1] is:

$$
I_i = c \cdot z_i \sum_j w_{ij} z_j
$$

In which $I_i$ is the Moran's Local Spatial Association Statistic, $z_i$ and $z_j$ corresponds to the value of the standardized variable in territorial unit $i$ and $j$, while $w_{ij}$ is each element of the row-standardized spatial weight matrix, and finally $c$ is a constant given by $\sum_i z_i^2$, the sum of the standardized variable value.

The $I_i$ can be represented in cluster map with four categories of territorial units: i) clusters of territorial units with high variable values surrounded by neighboring territorial units also with high values (High-High clusters); ii) clusters of territorial units with low variable values surrounded by neighbors with the same characteristic (Low-Low clusters); iii) clusters of territorial units with low variable values surrounded by neighbors with high values (Low-High clusters); and iv) clusters of territorial units with a high value variable surrounded by others with a low value (High-Low clusters).

When "high" or "low" is mentioned here, it is in relative terms, i.e., low or high values within the range of the information used. The last two categories, the Low-High and High-Low groups, identify territorial units as spatial outliers.

## Data sourse

To analyze the spatial distribution of the tourism activity in the CIP it is used information about establishment location linked to tourism sector for three years: 2010, 2020 and 2022. According to WNWTO and ILO [@UNWTO2014], there are 29 activities at industry group level (2 digits) in the North America Industrial Classification System (NACIS) that concern hospitality and tourism, which are called Tourism Characteristic Activities. The selected and used classification group the 29 activities in five types: i) accommodation, ii) food and beverage services, iii) recreation and entertainment, iv) transportation and v) travel services. Information on establishment location comes from National Statistical Directory of Economic Units (DENUE) and is provided as point vector layers, published by National Institute of Statistic and Geography (INEGI).

## Spatial areal unit

For this study, five municipalities were selected according the localization of the CIPs [@Fonatur2020]: Los Cabos y Loreto, both of them located in Baja California Sur, Ixtapa-Zihuatanejo in Zihuatanejo de Azueta municipality in Guerrero state, Cancún in Benito Juárez in Quintana Roo state and Bahías de Huatulco in Santa María Huatulco in Oaxaca state. Spatial information of the five municipalities comes from National Geostatistical Framework published by INEGI [-@INEGI2020mgn]. Using that five municipalities as overlay layer, five point layers of tourism establishments were generating in QGIS 3.22 using the clip geoprepossessing tool. To construct spatial autocorrelation indexes and clusters maps we use a first order queen spatial weight matrix.

# 4. Results and discussion

Total number of tourism establishments by year is presented in table 1. It is showed an important reduction of the number of establishments between 2010 and 2020, from 25% in Ixtapa-Zihuatanejo CIP to 54% in Huatulco CIP. Changes between 2020 and 2022 are less impressive, yet reflects a net reduction on tourist establishments. Comparing between these years is important as it reflects the balance of the pandemic and, as it can seen, recovering is almost complete.

**In which size establishment was reduction more importante and why**

ANNI is showed in table 2. For the five CIP and for each year ANNI is less than one, which means that actual distance is less than expected distance. In other words, ANNI indicates a very stable concentration point pattern in spatial distribution of tourism establishments in all CIP. Any change were not identified between 2020 and 2022, but minor ones from 2010 to 2020 with a marginal increase in ANNI of Loreto and Huatulco which means less concentration.

|         CIP        	|  2010 	|  2020 	|  2022 	|
|:------------------:	|:-----:	|:-----:	|:-----:	|
| Los Cabos          	| 1,614 	| 835   	| 798   	|
| Loreto             	| 220   	| 100   	| 101   	|
| Ixtapa-Zihuatanejo 	| 1,454 	| 377   	| 383   	|
| Cancún             	| 3,407 	| 1,212 	| 1,192 	|
| Bahías de Huatulco 	| 528   	| 290   	| 314   	|
| Total              	| 7,223 	| 2,814 	| 2,788 	|
: Table 1. Number of tourism establishments


|         CIP        	| 2010 	| 2020 	| 2022 	|
|:------------------:	|:----:	|:----:	|:----:	|
| Los Cabos          	| 0.08 	| 0.14 	| 0.14 	|
| Loreto             	| 0.28 	| 0.19 	| 0.19 	|
| Ixtapa-Zihuatanejo 	| 0.15 	| 0.20 	| 0.20 	|
| Cancún             	| 0.22 	| 0.24 	| 0.24 	|
| Bahías de Huatulco 	| 0.14 	| 0.14 	| 0.14 	|
: Table 2. Average Nearest Neighbor

The other results are shown in separate figures for each CIP. Each figure can be interpreted as a kind of 6x6 matrix. The first matrix row shows CIP´s geographical location, SDE with a ratio between major standard deviation ($SD_x$) and minor standard deviation ($SD_y$) which is called $RMM$ and legends map. SKD are shown in second row for each year and Cluster map are shown in third row accompanied by Moran´s I and a count of AGEB number in High-High category.

## Los Cabos

Located in the northwest of Mexico, in the Baja California Sur state (figure 1), Los Cabos CIP start operations in 1976. It is integrated for two settlements: San José del Cabo y Cabo San Lucas [@FONATURloscabos]. From almost 3 million of available rooms in January 2023, Los Cabos share 20% [@DataTur2023], which make this CIP the second in importance. The SDE for three years shows a large X-axis orientated from southwest (Cabo San Lucas) to northeast (San José del Cabo). From these them, Cabo San Lucas is the most important and the SDE covers this area the most, particularly around principal port. The $RMM$ is above 3, but gradually decrease, which indicate a more homogeneity shape beginning process, although dispersion and orientation does not change.

The SKD or heatmaps for Los Cabos exhibit two areas with tourism establishment spatial concentration, nevertheless the most important is at Cabo San Lucas. Moreover, high density area is gradually reduced in this period, always around main port which is accompanied by a establishment reduction from 2010 to 2020, and a little increase to 2022. 

The clusters maps include Moran´s I index and de number of AGEB included in High-High group. In this three years we found evidence of a moderate and significative spatial autocorrelation on tourism establishments per AGEB. The reduction of total establishments from 2010 to 2020 affects the magnitude of spatial autocorrelation and the number of spatial units in the HH cluster, but increasing the concentration around the main port have a positive impact on spatial autocorrelation in 2022.

**Insert Figure 1 near here**


## Loreto

Located in the same state as Los Cabos, Loreto CIP has not had the same success. The master plan of Loreto CIP was designed simultaneously with  Cancún´s, in late seventies, but start to operate in the nineties [@Sicilia2000; @FONATURloreto]. Loreto CIP include three settlements: Loreto, Nopoló and Puerto Escondido. The impact of this CIP is far from been as it was originally planned, since the number of visitors is considerable less than it was expected. Reasons are associated to a lack of connectivity and services [@Tulio2015].

The tourism establishments are extended from north in Loreto to south in Puerto Escondido, but the majority of establishments are located at Loreto. This is the reason for the extended form of the SDE for the three years. Moreover, the extension to south increased from 2010 to 2020 and 2022, changing the SDE shape but contributing to a shorter y-axis wich means less dispersion. The changes can be explained by a rise in tourism establishments in Nopoló and southern area of Loreto municipality. Nevertheless, the major and persistent concentration are located in Loreto, as it is showed by SKD, despite reduction of establishments: from more than two hundred to just one hundred. Significant spatial autocorrelation were identified, but their magnitude was between 0.342 and 0.406 and with only three or four AGEB in the HH cluster.

**Insert Figure 2 near here**


## Ixtapa-Zihuatanejo

This was the second CIP constructed by FONATUR in 1974 [@FONATURixtapa]. Tourism establishments are located in five settlements, from north to south: Pantla, San José Ixtapa, Ixtapa-Zihuatanejo (San José), Zihuatanejo and Coaoyul. Nevertheless, the most important concentration is in front of Zihuatanejo Bay. From 2010 to 2020 more than one thousand tourism establishments were closed, an almost 75% reduction. The SDE for the three years has a large x-axis orientated for Ixtapa-Zihuatanejo in northwest to Zihuatanejo, were the majority of the ellipse covers. The distance of the y-axis is reduced from 2010 to 2020 and 2022, since multiple tourism establishments were closed by the farest northern area of Zihuatanejo, which means a less spatial range or less dispersion reflected by $RMM$. The SKD is very stable since major concentration of tourism establishments appears almost constant in front of Zihuatanejo Bay, with a slighly increase in Ixtapa-Zihuatanejo (San José). Spatial autocorrelation is present, but weak relatively and decreasing, as well as the AGEB number in the HH cluster, nevertheless it appears a new HH cluster near San José which  could be reflect new business opportunities in this area.

**Insert Figure 3 near here**

## Cancún

Cancún CIP is the best known Mexican tourist destination in the World [@Fonatur2020] and the most success CIP of the Mexican government: it has 37.3% of the available room (January 2018) and 28.6% of the arrivals of non-resident tourists (January 2023). Cancún, located at municipality called Benito Juárez, has experimented a tremendous urbanization growth and it could be representative for the CIP contradictions: fast economic growth, but with environmental and social problems.

Tourism establishments seems to be distributed mainly in front of Cancún Port which affects considerably the SDE shape: it has x and y axes with very similar lengths. Tourims establishment reduction in Cancún between 2010 and 2020 was the second more important among CIPS. The reduction of tourism establishment number was considerable at north and west areas of Cancún which displaced and change SDE shape to southeast. $RMM$ shows a transition to a more homogeneous shape in studied period and it is explained by reduction of the establishment number.

These displacement can be seen in SKD maps with an area reduction of the major density, formerly along López Portillo Av.in 2010 and then with an increasing in eastern area known as Zona Hotelera. Cancún has the highest significant spatial autocorrelation among all CIPs, with values more than 0.55, nevertheless, magnitude is reducing gradually, as well as number of AGEB in HH cluster. Besides, cluster map shows relevance taken in the eastern area in Zona Hotelera.


**Insert Figure 4 near here**

## Bahías de Huatulco

Huatulco CIP was located at Oaxaca state and is integrated by Santa Cruz Huatulco and La Crucecita settlements, this one is the most important. As all CIP, Huatulco lost a considerable number of tourism establishments, but less than 45%. SDE shows a long x-axis which refers the relative location between the two towns: the first one in northwest and the second in southeast and this orientation has not changed from 2010 to 2022.  SDE covers La Crucecita almost entirely which means this town concentrate the majority of tourism establishments. Y-axis increases its length from 2010 to 2020 and 2022, which means a rise in spatial dispersion of the tourism establishments, mainly observed in La Crucecita area.

Major density area is relatively constant around La Crucecita between 2010 and 2020, but to 2022 showed an increase directed to coastal area. Besides it is possible to observe a marginal increase area density to eastern (Tangolunda Bay). Spatial autocorrelation on the tourism establishments is the lowest in Huatulco CIP and decreasing too, nevertheless HH AGEB number is constant.

**Insert Figure 5 near here**

## The five CIPs in perspective

As far as we know, this is the first study where the five original projected CIP are analysed simultaneously from a spatial perspective, particularly on spatial distribution of tourism establishments. This is only first step in knowing how spatial patters appears in different tourist destinations promoted by central Mexican government. Using different spatial analytical tools it was possible to know: orientation and dispersion, on one hand, and spatial concentration, on the ther, on tourism establishments between 2010 and 2022. 

Four CIP not had shown important visible orientation changes, only Cancún change orientation, which means increase in establishment number with different location for 2020 and 2022 compared with 2010. Different changes in dispersion were identified thought changes in length of y-axis. Huatulco, Loreto, Cacún and Los Cabos had increased dispersion, while Ixtapa had decrease. We remark the relatively homogeneity on orientation and, therefore stability in centripetal forces of economic tourism activities. Nevertheless, changes in orientation in Cancún need to be studied with more detail because they could associated to modification on location of centripetal forces of economic tourism activities in this area. The increase in dispersion is associated with the emergence of establishments relatively far from the main area of density, which is particularly true for Loreto and Huatulco.

Reduction on tourism establishments number was a notable characteristic. All CIPs showed an important reduction on number of tourism establishments from 2010 to 2020. These reduction were from minus 45% in Huatulco to minus 74% in Ixtapa. In all CIPs, this reduction was explained by small and medium establishments (SMEs) with less than 30 employees. This fact shows the fragility of this kind of firms and necessity to a in-deep study of them, since SMEs explain an important amount of employment in Mexico, particularly in service sector.

In this study, spatial patterns of tourism establishments was faced using three diferent tools: ANNI to measure concentration above all area, SKD to show high densities in defined areas by radio lengths, and cluster maps to show concentration measured as local interactions and variable levels simultaneously.  

Through ANNI, it was identified that in all cases and years there is a spatial concentration of points throughout the studied area. Changes were barely visible and actually marginal. While Los Cabos, Ixtapa, and Cancun showed less concentration throughout the area, Loreto and Huatulco exhibited more concentration.

Regarding the SKD, the reduction in the number of tourism establishments in each of the CIPs affected areas with higher density differently. While Los Cabos, Loreto, and Cancun showed a decrease in the area with higher density, Ixtapa and Huatulco did not show visible modifications in the size of the areas with higher density. However, in all cases, the absolute densities decreased, meaning the number of establishments per unit area was reduced.

The cluster maps revealed that in all cases, positive spatial autocorrelation was identified, meaning that there are AGEBs with a high number of establishments surrounded by others with similar characteristics. The concentration here, to the extent that these are no longer points but polygons, changes direction because proximity is by adjacency, not by distance, although the results of identifying high-high clusters coincide with previous instruments, particularly with the SKD.

The results of this exploratory research lead to the proposal of a new series of questions whose answers may provide elements to guide decisions of those responsible for promoting and developing CIPs, as well as entrepreneurs, administrators, and associations regarding business opportunities based on knowledge of the spatial distribution of economic activity in CIPs. Among them, we can enumerate: were the companies located in the areas of highest density the same in 2022 as in 2010? If so, what type of establishments were they in terms of size and tourist activity? What is the cause of the drastic decrease in the number of establishments between 2010 and 2020, and why did it mainly affect small and medium-sized enterprises? What is the relationship between the disappearance of companies and their distance from the most important concentration? The answer to these questions requires further research that we have only just begun.

# References








